package de.rwth.comsys.Enums;

public enum BSLCoreCommandsMSP430 {
	RX_DATA_BLOCK,
	RX_DATA_BLOCK_FAST,
	RX_PASSWORD,
	ERASE_SEGMENT,
	UNLOCK_AND_LOCK_INFO,
	ERASE_BLOCK,
	MASS_ERASE,
	CRC_CHECK,
	LOAD_PC,
	TX_BSL_VERSION,
	TX_BUFFER_SIZE;
}
